Traceback (most recent call last):
  File "/home/haxor/mambaforge/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/haxor/mambaforge/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/haxor/mambaforge/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 172, in wrapped
    return loop.run_until_complete(inner)
  File "/home/haxor/mambaforge/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/haxor/mambaforge/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/haxor/mambaforge/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/haxor/mambaforge/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd
A = pd.read_table("A_test2.txt", 
    header=None, 
    sep='\s+')
A
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mParserError[0m                               Traceback (most recent call last)
Cell [0;32mIn[10], line 2[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m
[0;32m----> 2[0m A [38;5;241m=[39m [43mpd[49m[38;5;241;43m.[39;49m[43mread_table[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mA_test2.txt[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m
[1;32m      3[0m [43m    [49m[43mheader[49m[38;5;241;43m=[39;49m[38;5;28;43;01mNone[39;49;00m[43m,[49m[43m [49m
[1;32m      4[0m [43m    [49m[43msep[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43m\[39;49m[38;5;124;43ms+[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m      5[0m A

File [0;32m~/mambaforge/lib/python3.10/site-packages/pandas/io/parsers/readers.py:1282[0m, in [0;36mread_table[0;34m(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, date_format, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, encoding_errors, dialect, on_bad_lines, delim_whitespace, low_memory, memory_map, float_precision, storage_options, dtype_backend)[0m
[1;32m   1269[0m kwds_defaults [38;5;241m=[39m _refine_defaults_read(
[1;32m   1270[0m     dialect,
[1;32m   1271[0m     delimiter,
[0;32m   (...)[0m
[1;32m   1278[0m     dtype_backend[38;5;241m=[39mdtype_backend,
[1;32m   1279[0m )
[1;32m   1280[0m kwds[38;5;241m.[39mupdate(kwds_defaults)
[0;32m-> 1282[0m [38;5;28;01mreturn[39;00m [43m_read[49m[43m([49m[43mfilepath_or_buffer[49m[43m,[49m[43m [49m[43mkwds[49m[43m)[49m

File [0;32m~/mambaforge/lib/python3.10/site-packages/pandas/io/parsers/readers.py:617[0m, in [0;36m_read[0;34m(filepath_or_buffer, kwds)[0m
[1;32m    614[0m     [38;5;28;01mreturn[39;00m parser
[1;32m    616[0m [38;5;28;01mwith[39;00m parser:
[0;32m--> 617[0m     [38;5;28;01mreturn[39;00m [43mparser[49m[38;5;241;43m.[39;49m[43mread[49m[43m([49m[43mnrows[49m[43m)[49m

File [0;32m~/mambaforge/lib/python3.10/site-packages/pandas/io/parsers/readers.py:1748[0m, in [0;36mTextFileReader.read[0;34m(self, nrows)[0m
[1;32m   1741[0m nrows [38;5;241m=[39m validate_integer([38;5;124m"[39m[38;5;124mnrows[39m[38;5;124m"[39m, nrows)
[1;32m   1742[0m [38;5;28;01mtry[39;00m:
[1;32m   1743[0m     [38;5;66;03m# error: "ParserBase" has no attribute "read"[39;00m
[1;32m   1744[0m     (
[1;32m   1745[0m         index,
[1;32m   1746[0m         columns,
[1;32m   1747[0m         col_dict,
[0;32m-> 1748[0m     ) [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_engine[49m[38;5;241;43m.[39;49m[43mread[49m[43m([49m[43m  [49m[38;5;66;43;03m# type: ignore[attr-defined][39;49;00m
[1;32m   1749[0m [43m        [49m[43mnrows[49m
[1;32m   1750[0m [43m    [49m[43m)[49m
[1;32m   1751[0m [38;5;28;01mexcept[39;00m [38;5;167;01mException[39;00m:
[1;32m   1752[0m     [38;5;28mself[39m[38;5;241m.[39mclose()

File [0;32m~/mambaforge/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py:234[0m, in [0;36mCParserWrapper.read[0;34m(self, nrows)[0m
[1;32m    232[0m [38;5;28;01mtry[39;00m:
[1;32m    233[0m     [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mlow_memory:
[0;32m--> 234[0m         chunks [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_reader[49m[38;5;241;43m.[39;49m[43mread_low_memory[49m[43m([49m[43mnrows[49m[43m)[49m
[1;32m    235[0m         [38;5;66;03m# destructive to chunks[39;00m
[1;32m    236[0m         data [38;5;241m=[39m _concatenate_chunks(chunks)

File [0;32mparsers.pyx:843[0m, in [0;36mpandas._libs.parsers.TextReader.read_low_memory[0;34m()[0m

File [0;32mparsers.pyx:904[0m, in [0;36mpandas._libs.parsers.TextReader._read_rows[0;34m()[0m

File [0;32mparsers.pyx:879[0m, in [0;36mpandas._libs.parsers.TextReader._tokenize_rows[0;34m()[0m

File [0;32mparsers.pyx:890[0m, in [0;36mpandas._libs.parsers.TextReader._check_tokenize_status[0;34m()[0m

File [0;32mparsers.pyx:2058[0m, in [0;36mpandas._libs.parsers.raise_parser_error[0;34m()[0m

[0;31mParserError[0m: Error tokenizing data. C error: Expected 3 fields in line 2, saw 4


